feat: create webhooks
equinor/terraform-azurerm-acr pull request #25
Opened 2022-12-08 09:01 UTC by helenakallekleiv

2022-12-08 09:15 UTC, nemanja-drobac commented on examples/webhook/README.md
> +Terraform configuration which creates an Azure Container Registry Webhook with the following features:
```suggestion
Terraform configuration which creates an Azure Container Registry included Webhook resource with the following features:
```

2022-12-08 09:25 UTC, nemanja-drobac commented on variables.tf
> +
```suggestion
variable "webhook" {
  description = "A list of objects required for this Webhook."
  type = list(object({
    name        = string
    service_uri = string
    actions     = list(string)
    status      = optional(string)
    scope       = optional(string)
  }))
  default = []
}

```

2022-12-08 09:48 UTC, hknutsen requested changes
Looks good 🙂 Left a few comments to make it consistent with other modules.

2022-12-08 09:48 UTC, hknutsen commented on main.tf
> +  registry_name       = var.registry_name
Get registry name from the container registry resource:

```suggestion
  name                = each.value.name
  registry_name       = azurerm_container_registry.this.name
```

This way, Terraform will create an automatic dependency between the webhook resources and the registry resource, removing the need of using the `depends_on` argument.

2022-12-08 09:48 UTC, hknutsen commented on variables.tf
> +}
Update variable name and description to better reflect that you can create multiple webhooks, and set type to map of objects and make some properties optional with default values:

```suggestion
variable "webhooks" {
  description = "A map of webhooks to create for this Container Registry."
  type = map(object({
    name        = string
    service_uri = string
    actions     = optional(list(string), ["push"])
    status      = optional(string, "enabled")
    scope       = optional(string, "")
  }))
  default = {}
```

By using maps, you could create two webhhooks `web` and `sql` using the following syntax:

```terraform
module "acr" {
  # source and arguments

  webhooks = {
    "web" = {
      # webhook properties
    }
    "sql" = {
      # webhook properties
    }
  }
}
```

Terraform would then create two webhook resources:

1. `module.acr.azurerm_container_registry_webhook.web`
2. `module.acr.azurerm_container_registry_webhook.sql`

This way, you have full control over the names of resources in your Terraform state file.

This is the same way we've done it for the other modules 🙂

2022-12-08 09:48 UTC, hknutsen commented on examples/webhook/main.tf
> +  ]
Update according to my suggested changes in `main.tf`:

```suggestion
  webhooks = {
    "this" = {
      name        = "mywebhook"
      service_uri = "https://mywebhookreceiver.example/mytag"
      actions     = ["push"]
      status      = "enabled"
      scope       = "mytag:*"
    }
  }
```

2022-12-12 09:27 UTC, helenakallekleiv commented
Go test passed on my local machine for all examples after committing suggestions.

2022-12-12 10:02 UTC, hknutsen approved these changes
Tests pass on my local machine.

Great work! 🙂

2022-12-12 10:04 UTC, merged